### ISSUE TITLE
New Tab button hides tabs

### ISSUE THREAD

**Issue by karai17** [jerone/atom-new-tab#5]
If I have a lot of tabs, they end up going behind the new tab button instead of the new tab button having its own dedicated space. It would be nice if this did not happen.

Also when I mouse over the new tab button, it gets bigger. I don't think it should do that.

**Comment by jerone** [comment]
Can you post a screenshot showing the problem.
Also what version of Atom & which theme are you using?

**Comment by karai17** [comment]
Atom 1.4, material ui theme. I can post a screenshot later

**Comment by jerone** [comment]
What version of Material UI, because I'm running that theme too on two instances (Windows) without problems?

**Comment by karai17** [comment]
Latest version on Linux.

**Comment by jerone** [comment]
I'm seeing this: ![2016-01-24 16_10_54-untitled c__users_jerone_documents_github_menu-manager atom](https://cloud.githubusercontent.com/assets/55841/12537011/1a3c306a-c2b5-11e5-8ac0-6647a06a1c3a.png)

The "New Tab"  button has it's own fixed space.

**Comment by karai17** [comment]
I'm half asleep atm, but i recall when i mouse over the new tab button, it
expands and blocks some tabs, and i had a tab go completely behind the new
tab button so i couldn't close it or select it without hotkeys.

**Comment by jerone** [comment]
> Latest version

The latest version is [v0.8.0](https://github.com/silvestreh/atom-material-ui/releases). A few weeks ago version [v1.0.#](https://github.com/silvestreh/atom-material-ui/commit/91424a3e3c9435a85fbd05e1d4143a63082e750c) was released and later pulled again when people reported a lot of bugs. The developer is since then working on a new v1.0.0 version. I'm kind of waiting for that version. Can you confirm you have version v0.8.0!

Previously people reported [similar issues](https://github.com/jerone/atom-new-tab/issues/3) with Material UI theme, but after fixing those since v0.8.0 I had no issues. If you can post a screenshot that would be great. Also any other package names that could interact with the core Tabs package?

**Comment by karai17** [comment]
Material 0.8.0, Monokai 0.18.0. Screenshot is when I am mousing over the new tab.

![new_tab](https://cloud.githubusercontent.com/assets/590332/12539825/055f55e8-c2d1-11e5-94c1-8752ba729d56.png)

**Comment by jerone** [comment]
New version of Material UI theme is released. If this is still an issue we can reopen this issue.
